### ISSUE TITLE
Implement Postgres model implementation to use with Heroku

### ISSUE THREAD

**Issue by himanshub16** [himanshub16/outbound-go#2]
Task is to create alternate database interfacing to let it use Postgres instead of MongoDB. 
Benefits:
One can use Heroku Postgres instead of MLabs.

**Comment by ghost** [comment]
I'll take a shot on this

**Comment by himanshub16** [comment]
Sure. :smiley: 

Sorry for late reply as I'd been bit busy during the weekend. Please go forward. I'll be happy to help.
